### PR TITLE
Mockifier NullPointer when BTSVersion = "2016"

### PR DESCRIPTION
**Pull request by Pauwelz**
The Mockifier throws a NullPointer exception when parsing the Bindings file if the BTSVersion is set to 2016 in the Deployment.btdfproj

This is due to the Resource.resx file not having the correct resources.

### CODE REVIEW

**Comment by svetvasilev** [comment]
Hi Michel and thanks for your contribution. Very well spotted. The reason why i havent addressed this earlier is that this behaviour is more of a pre- vs. post BizTalk 2013, rather than for a specific version. But i see now that it has caused some troubles when someone explicitly sets the BTSVersion property to 2016.

**Review by svetvasilev — CHANGES_REQUESTED** [review]
The only remark i have is about the comments on the new resource strings - they still speak about BizTalk 2013.

**Comment by Pauwelz** [comment]
Indeed, the issue only occurs when you explicitly set 2016 as BTSVersion.
It would work if you don't set anything, since they're the same for 2013 and 2016.
But for dummy proofing - that's how I found the issue - this might be a solution.

**Comment by svetvasilev** [comment]
Totally agree. Check my code review comments. Cheers

Den søn. 6. mai 2018, 10:21 skrev Michel Pauwels <notifications@github.com>:

**Comment by svetvasilev** [comment]
Hi Michel, were you able to fix the resources comments as per my review?
Cheers, Svet

**Comment by Pauwelz** [comment]
Hi,

Yes, I updated them already (https://github.com/svetvasilev/transmock/pull/8/commits/9b76d13ea6c5563609d130f62e0df19b3ee01f51).

Should be included in this pull request.

**Pull request merged**
